[tool.poetry]
name = "generic_qaoa"
version = "0.1.0"
description = ""
authors = ["Snir Bachar <snir@quantum-machines.co>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.23.1"
scipy = "^1.9.0"
qiskit = "^0.37.1"
matplotlib = "^3.5.2"
jupyter = "^1.0.0"
ipympl = "^0.9.1"
qiskit-ibm-runtime = "^0.6.2"
pylatexenc = "^2.10"
mypy = "^0.971"



[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

